stream:
  # 数据通道
  channel:
    # 接受通道
    sourceQueue:
      # 通道类型，目前支持：memory
      type: memory
      # 队列容量
      capacity: 20000
    # 发送通道
    sinkQueue:
      type: memory
      # 队列容量
      capacity: 20000
  # 消息源配置
  source:
    test:
      # 消息源类型，目前支持：local、mqtt、kafka、rabbitmq、redis、pulsar
      type: kafka
      # 关联通道
      channel: sourceQueue
      # 指定Kafka配置实例名称
      instance: kafka-client-consumer
      config:
        # 消费的topic，多个以逗号分隔
        topic: stream-1
    # 接受本地通道的数据，然后发送到Kafka Broker
    test2:
      type: local
      channel: sinkQueue
  # 消息目标配置
  sink:
    # 接受处理
    test:
      # 消息目标类型，目前支持：local、mqtt、kafka、rabbitmq、redis、pulsar
      type: default
      # 关联通道
      channel: sourceQueue
      # 目标由几个固定线程去处理
      threads: 2
    # 发送处理
    test2:
      type: kafka
      channel: sinkQueue
      threads: 1
      # 指定Kafka配置实例名称
      instance: kafka-client-producer

  # 客户端实例配置
  instance:
    kafka-client-consumer:
      # 转义.，其他消费者配置详见https://kafka.apache.org/documentation.html#consumerconfigs
      "[bootstrap.servers]": 192.168.6.196:9092
      "[group.id]": test1
    kafka-client-producer:
      # 转义.，其他生产者配置详见https://kafka.apache.org/documentation.html#producerconfigs
      "[bootstrap.servers]": 192.168.6.196:9092