stream:
  # 数据通道
  channel:
    # 接受通道名称
    sourceQueue:
      # 通道类型，目前支持：memory
      type: memory
      # 队列容量
      capacity: 20000
    # 发送通道名称
    sinkQueue:
      type: memory
      # 队列容量
      capacity: 20000
  # 消息源配置
  source:
    test:
      # 消息源类型，目前支持：local、mqtt、kafka、rabbitmq、redis、pulsar
      type: rabbitmq
      # 关联通道
      channel: sourceQueue
      # 指定实例名称
      instance: rabbitmq-client
      # 配置MQTT
      config:
        # exchange与queue进行绑定
        exchangeQueueBind:
          # exchange名称
          test-1:
            # queue名称
            queue: test-queue-1
            # 路由key
            routingKey: ""
    # 接受本地通道的数据，然后发送到RabbitMQ Server
    test2:
      type: local
      channel: sinkQueue
  # 消息目标配置
  sink:
    # 接受处理
    test:
      # 消息目标类型，目前支持：local、mqtt、kafka、rabbitmq、redis、pulsar
      type: default
      # 关联通道
      channel: sourceQueue
      # 目标由几个固定线程去处理
      threads: 2
    # 发送处理
    test2:
      type: rabbitmq
      channel: sinkQueue
      threads: 1
      # 指定实例名称
      instance: rabbitmq-client
  # 客户端实例配置
  instance:
    rabbitmq-client:
      virtualHost: rabbitmq_node1
      host: 192.168.6.196
      port: 5672
      username: admin
      password: admin