stream:
  # 数据通道
  channel:
    # 接受通道
    sourceQueue:
      # 通道类型，目前支持：memory
      type: memory
      # 队列容量
      capacity: 20000
    # 发送通道
    sinkQueue:
      type: memory
      # 队列容量
      capacity: 20000
  # 消息源配置
  source:
    test:
      # 消息源类型，目前支持：local、mqtt、kafka、rabbitmq、redis、pulsar
      type: redis
      # 关联通道
      channel: sourceQueue
      # 指定实例名称
      instance: redis-client
      config:
        topic: test/stream-1
    # 接受本地通道的数据，然后发送到MQTT Server
    test2:
      type: local
      channel: sinkQueue
  # 消息目标配置
  sink:
    # 接受处理
    test:
      # 消息目标类型，目前支持：default（local）、mqtt、kafka、rabbitmq、redis、pulsar
      type: default
      # 关联通道
      channel: sourceQueue
      # 目标由几个固定线程去处理
      threads: 1
    # 发送处理
    test2:
      type: redis
      channel: sinkQueue
      threads: 1
      # 指定实例名称
      instance: redis-client
  # 实例配置
  instance:
    redis-client:
      mode: single
      address: redis://192.168.6.196:6379
      password: hy123456
      database: 2