stream:
  # 数据通道
  channel:
    # 通道名称
    localQueue:
      # 通道类型，目前支持：memory
      type: memory
      # 队列容量
      capacity: 20000
  # 消息源配置
  source:
    test:
      # 消息源类型，目前支持：local、mqtt、kafka、rabbitmq
      type: local
      # 关联通道
      channel: localQueue
  # 消息目标配置
  sink:
    test:
      # 消息目标类型，目前支持：default、mqtt、kafka、rabbitmq
      type: default
      # 关联通道
      channel: localQueue
      # 目标由几个固定线程去处理
      threads: 1